### PR TITLE
Fix/pybindgen mem leaks

### PR DESCRIPTION
**Pull request by lowaa**
Updating pybindgen version, adding a very simple memory test and updating the version

### CODE REVIEW

**Review by DanielLeone — APPROVED** [review]
business as usual, memory seems fine to me :)

**Comment by smills2929** [comment]
Oh woops, I never approved this. Is this being used @lowaa ?

**Comment by lowaa** [comment]
> Oh woops, I never approved this. Is this being used @lowaa ?

hehe, it sure is

**Review by smills2929 — APPROVED** [review]
A-approved

**Pull request merged**
